---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: syncer
  namespace: lmxia
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: clusternet:controller-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: syncer
    namespace: lmxia
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: syncer
  namespace: lmxia
  labels:
    app: syncer
spec:
  selector:
    matchLabels:
      app: syncer
  template:
    metadata:
      labels:
        app: syncer
    spec:
      containers:
        - name: syncer
          image: lmxia/syncer:v1
          env:
            - name: SYNCER_NAMESPACE
              value: syncer-operator
            - name: SYNCER_CLUSTERID
              value: cluster1
            - name: BROKER_K8S_APISERVER
              value: 121.41.31.123:6443
            - name: BROKER_K8S_APISERVERTOKEN
              value: eyJhbGciOiJSUzI1NiIsImtpZCI6Im5wMXBzaFZoYTJKRjEwWWNQOTVNU3ZMWlVRTm5tZ3c1eHlTcC1HcnhUQWsifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJjb3JlMi1maWVsZDEtajdja3YiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlY3JldC5uYW1lIjoiZ2FpYS02NDJ6bS10b2tlbi00aGJnNSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJnYWlhLTY0MnptIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiMDIwYzE4YTItMzRlNS00MjMxLWJlZDUtYzFiYzE5YzAzMWNiIiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50OmNvcmUyLWZpZWxkMS1qN2NrdjpnYWlhLTY0MnptIn0.Rx6ePEuK547Ms3d404FjVM6y6fkwrCcceyWyteuGH_UZ1rXwyp0CRDRRrECU6NNLkp0rL1wyZwNV-9RkPiGaVr8QhET_mAs2pOrU3Nv2AMo_FiG5aolqTpkfOGN9GIQu3Il0QSAfOfjLkflS_lE6P_hJ-TPNcZp6qdCEj2wHdGCqTYhyJQfAVwBeCTl4dD6VuVOa5lXAYl0p2w1VOQpudysooK8Mspx1l8eqOecEst0JfeBJsLthbdsqFES63O1jer56wvfKkoaluvOFYdYGwKCslpRXARCTYnludwMiNehjEXSSmqrZzWBLmlQGb_bRoJ8asds-umAIfgxCH8boRQ
            - name: BROKER_K8S_REMOTENAMESPACE
              value: syncer-broker
            - name: BROKER_K8S_CA
              value: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM1ekNDQWMrZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJek1EUXhOekE0TURFeU5sb1hEVE16TURReE5EQTRNREV5Tmxvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBT2Z2CmVPM0pZSUhzYm1pTmtzZEhDb3MzeFg0MUZQdjZrakZVaXVkMHJyMzlWMnc1VTA4dU52RG15dHNSb3E4VjY0blYKYlp0TzJ4ZGNZWjRWQnBEOGE2eTIxc1NtaGt2OVVabVdUdkxLWWNoTHF4bUdxU25vTTR4bWRjQnEyL0I4T1ZtaQpSQ0ZxT2VhZndFbDNxVlYxWmprcnpBWW1XODRwRCtSZE1pRFJtdzJrNzBkY29BaGFhNmJsbzVvdXJLVXdIUG4xCjZpbVhCSEtvM1BDMjJoMDR2ZG1sYW0yNS81TnE0Y291dHlHcWpBSExickYrWCtTMGRnSHdYZFp5R1hyV1VIT20KV0M5bUFJc1VDbGdlQnkvZFlyQzAyS1hQV2xNRFlpbTJGQUpPMzdyTzZ4YjU4VUNNREdkTmZVM0FVNWtDVFVrcAp5cFozMUh1bjNRS1B5UGVRRjdFQ0F3RUFBYU5DTUVBd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZIbGR2RTlsN2VJWjhvODRrKytLT0VVV3JISWdNQTBHQ1NxR1NJYjMKRFFFQkN3VUFBNElCQVFESWtiRy9PaytJanBFTmU5SVhvNkNWUEZDdkNlelhZMG4wNEVOVXRWL1h0VnJ2U0lsVwpVODRBeEhzZXl5UjJINENrc1hIQm9vUjdMN2R0VGJyK3hNdEpSalIzODd0U1FPTkJ5SndXOENqOGVDQVF3Y2JECllWb3ZaSXF4MFVWUUNCSmxPWkpVS1pqVG5BRHNHVnZQZmFQSzZpcCtOQlplbEJqaWR6UldLWGNvSy9TRVZmdW8KcUx5elVTQzZ1UWR5cTEyaWZudituZnNJbDNXckFtMTBwcmFOZ1dUNnlTd3ZLaVg2TStMQXNMbzNYaFVDNVMrMQpWWGgxWGUvbkx6bjJvaEY1bFp0MHZnOUdUYzhaNk1WKzJLc09ld3ZXSUhPOHhLWFlXZklKWHM0YmJGVjFQNzgzCmtXNjlGek1lcnlFV0N1cWlMaHpueHVnb2VWQksxdEdSeGhsVgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
            - name: BROKER_K8S_INSECURE
              value: "false"
      serviceAccountName: syncer
